name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request: 
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: |
          if [ -f pubspec.yaml ]; then
            flutter pub get
          else
            echo "Archivo pubspec.yaml no encontrado en la raiz"
          fi

      - name: Analyze code
        run: |
          if [ -f pubspec.yaml ]; then
            flutter analyze
          else
            echo "Saltando analisis porque no se encontro el proyecto"
          fi
